#!/bin/sh

# Called from /etc/fstab to ensure we have something mounted at $1.
# This specific use-case is for /mnt, which ideally this is some type of
# persistent storage, by default an MTD device, but if that failed for
# some reason we fall back to 1) check for an partition labled "Config",
# or 2) worst-case a tmpfs.  This effectively brings up the system with
# the default configuration, but obviously any subsequent configuration
# is ephemeral.

set -e

mnt=$1

if mountpoint -q $mnt; then
    exit 0
fi

if mount LABEL="Config" $mnt; then
    exit 0
fi

logger -c -p user.crit -t $0 \
       "$mnt was not mounted, falling back to tmpfs."

mount -t tmpfs tmpfs-fallback $mnt
