#!/bin/sh

NAME=watchdogd
DAEMON=/usr/sbin/$NAME
DAEMONCTL=/usr/bin/watchdogctl
PIDFILE=/var/run/$NAME.pid
CFGFILE=/etc/default/$NAME

# Defaults to connect to /dev/watchdogd, use /etc/default/watchdogd
# to override DAEMON_ARGS.  Note: -x is safe exit.
DAEMON_ARGS="-x"

# Read configuration variable file if it is present
[ -f $CFGFILE ] && . $CFGFILE

start() {
	printf 'Starting %s: ' "$NAME"
	start-stop-daemon -S -q -p $PIDFILE -x $DAEMON -- $DAEMON_ARGS
	[ $? = 0 ] && echo "OK" || echo "FAIL"
}

stop() {
	printf 'Stopping %s: ' "$NAME"
	start-stop-daemon -K -q -p $PIDFILE -x $DAEMON
	[ $? = 0 ] && echo "OK" || echo "FAIL"
}

restart() {
	stop
	start
}

case "$1" in
    start|stop|restart)
	"$1"
	;;
    reload)
	$DAEMONCTL reload
	;;
    *)
	echo "Usage: $0 {start|stop|restart|reload}"
	exit 1
esac

exit $?
