#!/bin/sh
usage()
{
    cat <<EOF
Usage:
    qemu [-f qemu.cfg]
or
    qemu KERNEL INITRD

Environment variables that impact qemu:

    QEMU_ARCH - QEMU arch
	     *: Launch QEMU as qemu-system-\${QEMU_ARCH}
       default: None, mandatory

    QEMU_MACH - QEMU machine, with optional machine extras
	     *: Argument to QEMU -M \${QEMU_MACH}
       default: None, mandatory

    V - Show kernel boot messages
	   "1": Show boot messages
	     *: Silent kernel boot

    QEMU_APPEND - Commandline options to pass to the kernel
       default: None

    QEMU_DTB - Path to device tree to use
       default: No device tree

    QEMU_EXTRA - Commandline options to pass to QEMU
       default: None

    QEMU_GDB_KPORT - TCP port to listen for GDB connections to kernel
       default: 4711

    QEMU_GDB_KWAIT - Wait for user to attach to kernel before booting
       default: Don't wait

    QEMU_GDB_UPORT - TCP port to listen for GDB connections to userspace
       default: 4712

    QEMU_MNT - JFFS2 image to mount as /mnt
       default: None, mandatory

    QEMU_HOST - Directory to passthrough-mount (9p) as /host
       default: None, mandatory

    QEMU_N_NICS - Number of Network adapters
       default: 1

    QEMU_NIC - Network adapter model
       default: virtio-net

    QEMU_NET - Network mode
      "bridge": Bridge the quests interface to the host's QEMU_BRIDGE
	 "tap": Guest interface is exported as exported to host as qtap
       default: "bridge"

    QEMU_BRIDGE - Host-side bridge to attach interfaces to
       default: "virbr0"

EOF
}

# Return ${2} if set, else ${1}
default()
{
    [ -z ${2} ] && echo ${1} || echo ${2}
}

# debug        :: enable Finit debug mode, used to be --debug
# quiet        :: no kernel logs, except for warnings + errors
# rescue       :: enter rescue mode, bypasses all .conf files
# splash       :: display splash screen and progress bar
# single, or S :: enter single user mode, runlevel 1 or
append_args()
{
    if [ "${V}" != "1" ]; then
	echo -n "quiet "
    else
	echo -n "debug finit.debug=1 finit.show_status=0 "
    fi

    echo -n "${QEMU_APPEND} "
    echo -n "console=hvc0 "

    if [ "${1}" = "-r" ]; then
	# Size of initrd, rounded up to nearest kb
	size=$((($(find ${2} -printf %s)+1023) >> 10))
	echo -n "root=/dev/ram ramdisk_size=${size} "
	echo -n "block2mtd.block2mtd=/dev/sda,,Config "
    else
	echo -n "root=/dev/vda "
    fi
}

dtb_args()
{
    if [ -z ${QEMU_DTB} ]; then
	return
    fi

    echo -n "-dtb ${IMAGEDIR}/${QEMU_DTB}"
}

mnt_args()
{
    if [ -z "${QEMU_MNT}" ]; then
	[ -d ~/.cache ] || return
	QEMU_MNT=~/.cache/${NETBOX_VENDOR_ID}-config-${NETBOX_PLAT}.img

	# Transitional, rename any netbox-foo.img -> netbox-config-foo.img
	old=~/.cache/${NETBOX_VENDOR_ID}-${NETBOX_PLAT}.img
	[ -f $old ] && mv $old $QEMU_MNT
    fi

    if [ ! -e "${QEMU_MNT}" ]; then
	dd if=/dev/zero bs=16384 count=960 2>/dev/null | tr '\000' '\377' > "${QEMU_MNT}"
    fi

    echo -n "-device ${QEMU_SCSI},id=scsi0 "
    echo -n "-device scsi-hd,bus=scsi0.0,drive=drive0 "
    echo -n "-drive file=${QEMU_MNT},if=none,format=raw,discard=unmap,id=drive0 "
}

host_args()
{
    [ -z "${QEMU_HOST}" ] && return

    echo -n "-virtfs local,path=${QEMU_HOST},security_model=none,mount_tag=hostfs "
}

net_args()
{
    brname=${QEMU_BRIDGE:-virbr0}
    model=${QEMU_NIC}
    mode=${QEMU_NET:-bridge}

    for n in $(seq 0 $((${QEMU_N_NICS:-1} - 1)) ); do
	if [ "${mode}" = "bridge" -a ${n} -eq 0 ]; then
	    # new style -nic config allows no ifname in bridged mode
	    echo -n "-nic bridge,br=${brname}"
	else
	    # ignore any enslave script for unbridged ports
	    echo -n "-nic tap,ifname=qtap${n},script=no"
	fi

	# Use qemu-system default if no model is given
	if [ -n "${model}" ]; then
	    echo -n ",model=${model} "
	else
	    echo -n " "
	fi
    done
}

consle_args()
{
    echo -n "-device virtio-serial "

    echo -n "-chardev stdio,mux=on,id=hvc0 "
    echo -n "-device virtconsole,chardev=hvc0 "

    echo -n "-mon chardev=hvc0 "
}

gdb_args()
{
    echo -n "-gdb tcp::${QEMU_GDB_KPORT:-4711} "
    if [ ! -z ${QEMU_GDB_KWAIT} ]; then
        echo -n "-S "
    fi

    addr="port=${QEMU_GDB_UPORT:-4712},host=localhost"
    echo -n "-chardev socket,id=hvc1,${addr},server,nowait "
    echo -n "-device virtconsole,name=gdb,chardev=hvc1"
}

# Assume available from current directory
dir=.
cfg=qemu.cfg

case $1 in
    -f)
	if [ ! -r $2 ]; then
	    echo "qemu: Config file $2 is not readable."
	    usage
	    exit 1
	fi
	dir=$(dirname $2)
	cfg=$(basename $2)
	;;
    *)
	QEMU_KERNEL=$1
	QEMU_MACH=$2
	;;
esac

# Source default or -f config
if [ -z "${QEMU_MACH}"  -o -z "${QEMU_KERNEL}" ]; then
	. "$dir/$cfg"
fi

if [ -z "${QEMU_ARCH}" -o -z "${QEMU_MACH}"  -o -z "${QEMU_KERNEL}" ]; then
    echo "qemu: One or more of the following are missing"
    echo "QEMU_ARCH   : $QEMU_ARCH"
    echo "QEMU_MACH   : $QEMU_MACH"
    echo "QEMU_KERNEL : $QEMU_KERNEL"
    exit 1;
fi

# Disable pulseaudio warning
export QEMU_AUDIO_DRV=none

# Save current line settings, then disable all of them so that
# everything is passed through to the guest (C-c, C-z etc.).
line=$(stty -g)
stty raw

# Start Qemu
if [ -n "${QEMU_INITRD}" ]; then
    qemu-system-${QEMU_ARCH} -display none -m 256M		\
		-M ${QEMU_MACH} ${QEMU_EXTRA}			\
		-kernel ${QEMU_KERNEL} -initrd ${QEMU_INITRD} 	\
		-append "$(append_args -r ${QEMU_INITRD})"	\
		$(dtb_args) $(mnt_args) $(host_args) $(net_args)\
		$(consle_args) $(gdb_args)
else
    qemu-system-${QEMU_ARCH} -display none -m 256M		\
		-M ${QEMU_MACH} ${QEMU_EXTRA}			\
		-kernel ${QEMU_KERNEL}				\
    		-drive file=${QEMU_DISK},if=virtio,format=raw	\
		-append "$(append_args -d ${QEMU_DISK})"	\
		$(dtb_args) $(mnt_args) $(host_args) $(net_args)\
		$(consle_args) $(gdb_args)
fi

# Restore TTY from Qemu target
stty ${line}
